---
# This ZTP has dependency on a management cluster
######
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"

commonLabels:
  telco-gitops/ztp: combined-ran

resources:
  - 01-agent-ocpsmc.yaml
  - 01-cluster-ocpsmc.yaml
  - 01-infraenv-ocpsmc.yaml
#  - 01-nmstate-ocpsmc.yaml
  - 01-nmstate-ocpsmc-dhcp.yaml
#  - 02-bmh-ocpsmc.yaml
#  - 02-bmh-ocpsmc-3m.yaml
