---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "30"

bases:
  # Operators for MGMT Clusters
  - ../../../blueprints/mgmt

resources:
