apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeDiscovery
metadata:
  name: auto-discover-devices
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
#          - key: ran.openshift.io/lso
#            operator: Exists
          - key: kubernetes.io/hostname
            operator: In
            values:
              - master1.aitest01.telcolab.sg
              - master2.aitest01.telcolab.sg
              - master3.aitest01.telcolab.sg