---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "30"

#commonAnnotations:
#  argocd.argoproj.io/sync-wave: "30"

resources:
  - 05-telco-gitops-chart.yaml
