---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
  name: ztp-{{ .Values.name }}-wait-job
  namespace: telco-gitops
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30
      containers:
        - image: registry.redhat.io/openshift-gitops-1/argocd-rhel8:v1.2.0
          imagePullPolicy: IfNotPresent
          name: ztp-{{ .Values.name }}-wait-argocd
          env:
            - name: SLEEP
              value: "3"
          command:
            - /bin/bash
            - -c
            - |
              ZWNobyAiSGVsbSBQcmVJbnN0YWxsIEhvb2sgdG8gd2FpdCBmb3IgdGFyZ2V0IGNsdXN0ZXIgZGVmaW5pdGlvbiBpbiBBcmdvQ0QiClVSTF9SRUFEWT0iUGF1c2luZyAkU0xFRVAgc2Vjb25kcy4uLiIKd2hpbGUgWyAiJFVSTF9SRUFEWSIgIT0gImh0dHBzIiBdOyBkbwplY2hvICJXYWl0aW5nIGZvciB0aGUgQUkgc3RhdHVzIFVSTCB0byBiZSByZWFkeS4gKCRVUkxfUkVBRFkpIgpzbGVlcCAkU0xFRVAKVVJMPSQob2MgLW4ge3sgLlZhbHVlcy5uYW1lc3BhY2UgfX0gZ2V0IGFnZW50Y2x1c3Rlcmluc3RhbGxzLmV4dGVuc2lvbnMuaGl2ZS5vcGVuc2hpZnQuaW8gYWNpLXt7IC5WYWx1ZXMubmFtZSB9fSAtbz1qc29ucGF0aD0iey5zdGF0dXMuZGVidWdJbmZvLmV2ZW50c1VSTH0iKQpVUkxfUkVBRFk9JChlY2hvICRVUkwgfCBhd2sgLUYgIjoiICd7cHJpbnQgJDF9JykKZG9uZQpJTlNUQUxMX1NUQVRVUz0iV2FpdGluZyBmb3IgaW5zdGFsbCB0byBjb21wbGV0ZSIKd2hpbGUgWyAiJElOU1RBTExfU1RBVFVTIiAhPSAiU3VjY2Vzc2Z1bGx5IGZpbmlzaGVkIGluc3RhbGxpbmcgY2x1c3RlciIgXTsgZG8KZWNobyAiV2FpdGluZyBmb3IgdGhlIGNsdXN0ZXIgdG8gY29tcGxldGUgaW5zdGFsbGF0aW9uLiAoJElOU1RBTExfU1RBVFVTKSIKc2xlZXAgJFNMRUVQCiMgSU5TVEFMTF9TVEFUVVM9JCggY3VybCAtcyAtayAkVVJMIHwganEgLlstMTpdWzBdLm1lc3NhZ2UgKQpJTlNUQUxMX1NUQVRVUz0kKCBjdXJsIC1zIC1rICRVUkwgfCBhd2sgLUYgJyInICd7cHJpbnQgJChORi01KX0nICkKZG9uZQpvYyBnZXQgc2VjcmV0IC1uIHt7IC5WYWx1ZXMubmFtZXNwYWNlIH19IGNsdXN0ZXIte3sgLlZhbHVlcy5uYW1lIH19LWFkbWluLWt1YmVjb25maWcgLW8ganNvbnBhdGg9ey5kYXRhLmt1YmVjb25maWd9IHwgYmFzZTY0IC1kID4gL3RtcC9rdWJlY29uZmlnCkFSR09QVz0kKG9jIGdldCBzZWNyZXQgLW4gdGVsY28tZ2l0b3BzIHRlbGNvLWdpdG9wcy1jbHVzdGVyIC1vIGdvLXRlbXBsYXRlPSd7eyAie3siIH19aW5kZXggLmRhdGEgImFkbWluLnBhc3N3b3JkInt7ICJ9fSIgfX0nIHwgYmFzZTY0IC1kKQphcmdvY2QgLS11c2VybmFtZT1hZG1pbiAtLXBhc3N3b3JkPSRBUkdPUFcgLS1pbnNlY3VyZSAtLWNvbmZpZyAvdG1wL2NvbmZpZyBsb2dpbiB0ZWxjby1naXRvcHMtc2VydmVyLXRlbGNvLWdpdG9wcy5hcHBzLm9jcHNtYy5sYWIuZGlrdGlvLm5ldApERUZJTkVEX1NUQVRVUz0iV2FpdGluZyEiCmVjaG8gLW4gIldhaXRpbmcgZm9yIGNsdXN0ZXIgdG8gYmUgZGVmaW5lZCBpbiBBcmdvQ0QuIgp3aGlsZSAhIGBhcmdvY2QgY2x1c3RlciBsaXN0IHwgZWdyZXAgLXEgYXBpLnt7IC5WYWx1ZXMubmFtZSB9fS57eyAuVmFsdWVzLmRvbWFpbiB9fWA7IGRvCmVjaG8gLW4gIi4iCnNsZWVwICRTTEVFUApkb25lCmVjaG8gIkRlZmluZWQhIgphcmdvY2QgY2x1c3RlciBhZGQgLS1jb25maWcgL3RtcC9jb25maWcgLS1rdWJlY29uZmlnIC90bXAva3ViZWNvbmZpZyBhZG1pbiAtLW5hbWUgdGVsY28tb2NwdGVzdAphcmdvY2QgbG9nb3V0IC0tY29uZmlnIC90bXAvY29uZmlnIGFkbWluCnJtIC1mIC90bXAva3ViZWNvbmZpZyAvdG1wL2NvbmZpZyAKZWNobyAiQWxsIGRvbmUhIEhvb3JheSEiCnNsZWVwICRTTEVFUAo=
