---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: telco-ztp-gitops
  namespace: telco-gitops
spec:
  generators:
  - git:
      repoURL: {{ .Values.base_git_url }}
      revision: HEAD 
      directories:
        - path: clusters/*
  template:
    metadata:
      name: '01-ztp-gitops-{{ "{{" }}path.basename{{ "}}" }}'
      namespace: telco-gitops
    spec:
      destination:
        namespace: telco-gitops
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        repoURL: {{ .Values.base_git_url }}
        targetRevision: HEAD
        path: '{{ "{{" }}path{{ "}}" }}/ztp-gitops-app-sets'
      syncPolicy:
        automated:
          # Default prune is "false" 
          prune: true
          selfHeal: true 
          # Allows deleting all application resources during automatic syncing ( false by default ).
          allowEmpty: true
        syncOptions:
          # (equivalent to 'kubectl apply --validate=false')
          - Validate=false
          - CreateNamespace=true
          # Supported policies are background, foreground and orphan.
          - PrunePropagationPolicy=foreground
          # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
          - PruneLast=true
        retry:
          # unlimited if less than 0
          limit: -1
          backoff:
            # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
            duration: 1m
            # a factor to multiply the base duration after each failed retry
            factor: 2
            # the maximum amount of time allowed for the backoff strategy
            maxDuration: 3m
      # Ignore differences at the specified json pointers
      # ignoreDifferences:
      # - group: apps
      #   kind: Deployment
      #   jsonPointers:
      #   - /spec/replicas
      # ignoreDifferences:
      #    - group: apiextensions.k8s.io
      #      name: pcap.fennecproject.io
      #      kind: CustomResourceDefinition
      #      jsonPointers:
      #        - /spec/podLabel
      #        - /spec/interfaceName
      #        - /spec/packetCount
