---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-{{ .Values.name }}-{{ .Values.global.name }}
  namespace: assisted-installer
  labels:
    cluster-name: {{ .Values.global.name }}-nmstate
spec:
  config:
    interfaces:
      - name: bond0
        type: bond
        state: up
        mtu: 8996
        ipv4:
          enabled: true
          address:
            - ip: {{ .Values.bond0_IP }}
              prefix-length: 24
          dhcp: false
        link-aggregation:
          mode: active-backup
          options:
            miimon: '150'
          slaves:
          - {{ .Values.int1_name | quote }}
          - {{ .Values.int2_name | quote }}
      - name: {{ .Values.int3_name | quote }}
        type: ethernet
        state: down
        mtu: 8996
        ipv4:
          enabled: false
          dhcp: false
    dns-resolver:
      config:
        server:
          - '{{ .Values.global.dns }}'
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: {{ .Values.global.default_router }}
          next-hop-interface: bond0
  interfaces:
    - name: {{ .Values.int1_name | quote }}
      macAddress: {{ .Values.int1_mac | quote }}
    - name: {{ .Values.int2_name | quote }}
      macAddress: {{ .Values.int2_mac | quote }}
    - name: {{ .Values.int3_name | quote }}
      macAddress: {{ .Values.int3_mac | quote }}
