---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-{{ .Values.name }}-{{ .Values.global.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    cluster-name: {{ .Values.global.name }}-nmstate
spec:
  config:
    interfaces:
      - name: {{ .Values.int1_name }}
        type: ethernet
        state: up
        mtu: 8996
        ipv6:
          enabled: false
        ipv4:
          enabled: true
          dhcp: true
      - name: {{ .Values.int2_name }}
        type: ethernet
        state: up
        mtu: 8996
        ipv6:
          enabled: false
        ipv4:
          enabled: true
      - name: {{ .Values.int3_name }}
        type: ethernet
        state: up
        mtu: 8996
        ipv6:
          enabled: false
        ipv4:
          enabled: true
  interfaces:
    - name: {{ .Values.int1_name | quote }}
      macAddress: {{ .Values.int1_mac | quote }}
    - name: {{ .Values.int2_name | quote }}
      macAddress: {{ .Values.int2_mac | quote }}
    - name: {{ .Values.int3_name | quote }}
      macAddress: {{ .Values.int3_mac | quote }}
