---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-{{ .Values.name }}-{{ .Values.global.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    cluster-name: {{ .Values.global.name }}-nmstate
spec:
  config:
    interfaces:
      - name: bond0
        type: bond
        state: up
        mtu: 8996
        ipv4:
          enabled: true
        ipv6:
          enabled: false
        link-aggregation:
          mode: active-backup
          options:
            miimon: '150'
            primary: {{ .Values.int1_name | quote }}
          slaves:
          - {{ .Values.int1_name }}
          - {{ .Values.int2_name }}
  interfaces:
    - name: {{ .Values.int1_name | quote }}
      macAddress: {{ .Values.int1_mac | quote }}
    - name: {{ .Values.int2_name | quote }}
      macAddress: {{ .Values.int2_mac | quote }}
