---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-master1-ocptest-lab
  namespace: assisted-installer
data:
  username: cm9vdA==
  password: UmVkaGF0MDEK
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-master2-ocptest-lab
  namespace: assisted-installer
data:
  username: cm9vdA==
  password: UmVkaGF0MDEK
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-master3-ocptest-lab
  namespace: assisted-installer
data:
  username: cm9vdA==
  password: UmVkaGF0MDEK
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-worker1-ocptest-lab
  namespace: assisted-installer
data:
  username: cm9vdA==
  password: UmVkaGF0MDEK
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-worker2-ocptest-lab
  namespace: assisted-installer
data:
  username: cm9vdA==
  password: UmVkaGF0MDEK
type: Opaque
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: master1-ocptest-lab
  namespace: assisted-installer
  labels:
    # InfraEnv to use
    infraenvs.agent-install.openshift.io: "infraenv-core-ocptest-lab"
  annotations:
    bmac.agent-install.openshift.io/role: master
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/installer-args: '["-n"]' 
spec:
  online: true
  bootMACAddress: 52:54:00:e9:0e:fd
  automatedCleaningMode: disabled
  hardwareProfile: libvirt
  bmc:
    address: redfish-virtualmedia+http://192.19.130.14:8080/redfish/v1/Systems/fca82a04-b29b-4c3b-a35b-505426ece8cd
    credentialsName: bmc-master1-ocptest-lab
    disableCertificateVerification: True
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: master2-ocptest-lab
  namespace: assisted-installer
  labels:
    infraenvs.agent-install.openshift.io: "infraenv-core-ocptest-lab"
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/role: master
    bmac.agent-install.openshift.io/installer-args: '["-n"]' 
spec:
  online: true
  bootMACAddress: 52:54:00:96:aa:61
  automatedCleaningMode: disabled
  hardwareProfile: libvirt
  bmc:
    address: redfish-virtualmedia+http://192.19.130.14:8080/redfish/v1/Systems/b7f25171-79f0-4b62-abd7-e2dcf3f8e26c
    credentialsName: bmc-master2-ocptest-lab
    disableCertificateVerification: True
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: master3-ocptest-lab
  namespace: assisted-installer
  labels:
    infraenvs.agent-install.openshift.io: "infraenv-core-ocptest-lab"
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/role: master
    bmac.agent-install.openshift.io/installer-args: '["-n"]' 
spec:
  online: true
  bootMACAddress: 52:54:00:65:65:56
  automatedCleaningMode: disabled
  hardwareProfile: libvirt
  bmc:
    address: redfish-virtualmedia+http://192.19.130.14:8080/redfish/v1/Systems/e76d7a37-3d66-448a-b1a9-bdf15ea5d70b
    credentialsName: bmc-master3-ocptest-lab
    disableCertificateVerification: True
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: worker1-ocptest-lab
  namespace: assisted-installer
  labels:
    infraenvs.agent-install.openshift.io: "infraenv-core-ocptest-lab"
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/role: worker
    bmac.agent-install.openshift.io/installer-args: '["-n"]' 
spec:
  online: true
  bootMACAddress: 52:54:00:46:8a:bf
  automatedCleaningMode: disabled
  hardwareProfile: libvirt
  bmc:
    #address: idrac-virtualmedia://172.28.11.35/redfish/v1/Systems/System.Embedded.1
    address: redfish-virtualmedia+http://192.19.130.14:8080/redfish/v1/Systems/703b2501-d974-459f-92c6-4b42642ccb24
    credentialsName: bmc-worker1-ocptest-lab
    disableCertificateVerification: True
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: worker2-ocptest-lab
  namespace: assisted-installer
  labels:
    infraenvs.agent-install.openshift.io: "infraenv-core-ocptest-lab"
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/role: worker
    bmac.agent-install.openshift.io/installer-args: '["-n"]' 
spec:
  online: true
  bootMACAddress: 52:54:00:33:3e:ea
  automatedCleaningMode: disabled
  hardwareProfile: libvirt
  bmc:
    #address: idrac-virtualmedia://172.28.11.36/redfish/v1/Systems/System.Embedded.1
    address: redfish-virtualmedia+http://192.19.130.14:8080/redfish/v1/Systems/f39e30d4-76d2-444e-bc48-d349edbaa308
    credentialsName: bmc-worker2-ocptest-lab
    disableCertificateVerification: True
