---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: cluster-{{ .Values.global.name }}
  namespace: assisted-installer
spec:
  baseDomain: lab.diktio.net
  clusterName: {{ .Values.global.name }}
  controlPlaneConfig:
    servingCertificates: {}
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: aci-{{ .Values.global.name }}
    version: v1beta1
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          telco-core: core-{{ .Values.global.name }}
  pullSecretRef:
    name: {{ .Values.global.pull_secret }}
