---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#commonAnnotations:
#  argocd.argoproj.io/sync-wave: "10"

bases:
  # Quay Enterprise MGMT regisrty
  - ../../../base/configs/quay-mgmt-registry


resources:
