---
apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  annotations:
    unsupported.agent-install.openshift.io/assisted-service-configmap: assisted-service-config
  name: agent
spec:
  databaseStorage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 25Gi
  filesystemStorage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 25Gi
  mirrorRegistryRef:
    name: mirror-registry-config-map
  osImages:
    - openshiftVersion: '4.8'
      version: 48.84.202107202156-0
      #cpuArchitecture: x86_64
      rootFSUrl: >-
        http://hypervisor1.lab.diktio.net:8989/openshift-v4/dependencies/rhcos/4.8/4.8.2/rhcos-live-rootfs.x86_64.img
      url: >-
        http://hypervisor1.lab.diktio.net:8989/openshift-v4/dependencies/rhcos/4.8/4.8.2/rhcos-4.8.2-x86_64-live.x86_64.iso
