---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  name: presync-append-local-pull-secret-job
  namespace: telco-gitops
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-tools-rhel8:latest
        #registry.redhat.io/openshift4/ose-cli:latest
          imagePullPolicy: IfNotPresent
          name: local-pull-job
          command:
            - /bin/bash
            - -c
            - |
              echo "Adding local pull secret to the global one."
              cd /tmp
              oc extract secret/pull-secret -n openshift-config --confirm
              cat .dockerconfigjson | \
                  jq --compact-output '.auths["lab-registry.ocpsmc.lab.diktio.net/nsatsia"] |= . + {"auth":"bnNhdHNpYTpSZWRoYXQwMQ=="}' \
                  > new_dockerconfigjson
              oc set data secret/pull-secret -n openshift-config --from-file=.dockerconfigjson=new_dockerconfigjson
              rm -f .dockerconfigjson new_dockerconfigjson
              echo "All done! Hooray!"
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30