---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 02-hiveconfig.yaml
- 03-clusterimageset-4.8.11.yaml
# - 03-clusterimageset-4.8.0-nightly.yaml
# - 03-clusterimageset-4.8.x.yaml
