---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "50"

resources:
  - 00-hook-presync-csv.yaml
  # - 01-ocs-storagecluster-external.yaml
  - 01-ocs-storagecluster-internal.yaml
  - 99-hook-postsync-csv.yaml
