---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - 00-lso-volumes.yaml
  - 00-hook-presync-csv.yaml
  # - 01-ocs-storagecluster-external.yaml
  - 01-ocs-storagecluster-internal.yaml
  - 99-hook-postsync-csv-class-default.yaml
