---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "51"

resources:
  - 00-hook-presync-csv.yaml
  - 01-lab-registry-secret.yaml
  - 02-mgmtregistry.yaml
