---
# To manually create this file from pull-secret.json
# oc create secret generic assisted-deployment-pull-secret -n assisted-installer --from-file=.dockerconfigjson=pull-secret.json --type=kubernetes.io/dockerconfigjson
apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
  namespace: assisted-installer
  # namespace: open-cluster-management
data:
  .dockerconfigjson: >-
    e2F1dGhzOntsYWItcmVnaXN0cnkub2NwbWdtdC5sYWIuZGlrdGlvLm5ldDp7YXV0aDpibk5oZEhOcFlUcFNaV1JvWVhRd01RPT0sZW1haWw6bnNhdHNpYUByZWRoYXQuY29tfSxsYWItcmVnaXN0cnkub2Nwc21jLmxhYi5kaWt0aW8ubmV0OnthdXRoOmJuTmhkSE5wWVRwU1pXUm9ZWFF3TVE9PSxlbWFpbDpuc2F0c2lhQHJlZGhhdC5jb219LHF1YXkuaW86e2F1dGg6Ym5OaGRITnBZVHBTWldSb1lYUXdNUT09LGVtYWlsOm5zYXRzaWFAcmVkaGF0LmNvbX0scmVnaXN0cnkucmVkaGF0LmlvOnthdXRoOmJuTmhkSE5wWVRwU1pXUm9ZWFF3TVE9PSxlbWFpbDpuc2F0c2lhQHJlZGhhdC5jb219fX0K
type: kubernetes.io/dockerconfigjson
