---
# To manually create this file from pull-secret.json
# oc create secret generic assisted-deployment-pull-secret -n assisted-installer --from-file=.dockerconfigjson=pull-secret.json --type=kubernetes.io/dockerconfigjson
apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
  namespace: assisted-installer
  # namespace: open-cluster-management
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJsYWItcmVnaXN0cnkub2NwbWdtdC5sYWIuZGlrdGlvLm5ldCI6eyJhdXRoIjoiYm5OaGRITnBZVHBTWldSb1lYUXdNUT09IiwiZW1haWwiOiJuc2F0c2lhQHJlZGhhdC5jb20ifSwibGFiLXJlZ2lzdHJ5Lm9jcHNtYy5sYWIuZGlrdGlvLm5ldCI6eyJhdXRoIjoiYm5OaGRITnBZVHBTWldSb1lYUXdNUT09IiwiZW1haWwiOiJuc2F0c2lhQHJlZGhhdC5jb20ifSwicXVheS5pbyI6eyJhdXRoIjoiYm5OaGRITnBZVHBTWldSb1lYUXdNUT09IiwiZW1haWwiOiJuc2F0c2lhQHJlZGhhdC5jb20ifSwicmVnaXN0cnkucmVkaGF0LmlvIjp7ImF1dGgiOiJibk5oZEhOcFlUcFNaV1JvWVhRd01RPT0iLCJlbWFpbCI6Im5zYXRzaWFAcmVkaGF0LmNvbSJ9fX0K
type: kubernetes.io/dockerconfigjson
