---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-master1-ocpsmc-lab
  namespace: assisted-installer
data:
  username: cm9vdA==
  password: UmVkaGF0MDEK
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-master2-ocpsmc-lab
  namespace: assisted-installer
data:
  username: cm9vdA==
  password: UmVkaGF0MDEK
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-master3-ocpsmc-lab
  namespace: assisted-installer
data:
  username: cm9vdA==
  password: UmVkaGF0MDEK
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-worker1-ocpsmc-lab
  namespace: assisted-installer
data:
  username: cm9vdA==
  password: UmVkaGF0MDEK
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-worker2-ocpsmc-lab
  namespace: assisted-installer
data:
  username: cm9vdA==
  password: UmVkaGF0MDEK
type: Opaque
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: master1-ocpsmc-lab
  namespace: assisted-installer
  labels:
    # InfraEnv to use
    infraenvs.agent-install.openshift.io: "infraenv-core-ocpsmc-lab"
  annotations:
    bmac.agent-install.openshift.io/role: master
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/installer-args: '["-n"]' 
spec:
  online: true
  bootMACAddress: 52:54:00:e9:0e:fd
  automatedCleaningMode: disabled
  hardwareProfile: libvirt
  bmc:
    address: redfish-virtualmedia+http://192.19.130.14:8080/redfish/v1/Systems/f84f2702-b86f-4561-8c3a-da6780c80d53
    credentialsName: bmc-master1-ocpsmc-lab
    disableCertificateVerification: True
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: master2-ocpsmc-lab
  namespace: assisted-installer
  labels:
    infraenvs.agent-install.openshift.io: "infraenv-core-ocpsmc-lab"
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/role: master
    bmac.agent-install.openshift.io/installer-args: '["-n"]' 
spec:
  online: true
  bootMACAddress: 52:54:00:96:aa:61
  automatedCleaningMode: disabled
  hardwareProfile: libvirt
  bmc:
    address: redfish-virtualmedia+http://192.19.130.14:8080/redfish/v1/Systems/bc7b9994-6b56-473d-9af3-f30214cd97ca
    credentialsName: bmc-master2-ocpsmc-lab
    disableCertificateVerification: True
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: master3-ocpsmc-lab
  namespace: assisted-installer
  labels:
    infraenvs.agent-install.openshift.io: "infraenv-core-ocpsmc-lab"
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/role: master
    bmac.agent-install.openshift.io/installer-args: '["-n"]' 
spec:
  online: true
  bootMACAddress: 52:54:00:65:65:56
  automatedCleaningMode: disabled
  hardwareProfile: libvirt
  bmc:
    address: redfish-virtualmedia+http://192.19.130.14:8080/redfish/v1/Systems/648cc9ec-fb18-4ab6-9c05-6feb63a76403
    credentialsName: bmc-master3-ocpsmc-lab
    disableCertificateVerification: True
