
# https://github.com/openshift/assisted-service/blob/master/docs/operator.md#specifying-environmental-variables-via-configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: assisted-service-config
  # namespace: assisted-installer
  namespace: open-cluster-management
data:
  LOG_LEVEL: "debug"
  SUPPORT_L2: "false"
#  DISABLED_HOST_VALIDATIONS: "belongs-to-machine-cidr,belongs-to-majority-group"
  ISO_IMAGE_TYPE: "full-iso"
  PUBLIC_CONTAINER_REGISTRIES: "lab-registry.ocpsmc.lab.diktio.net"
  CONTROLLER_IMAGE: "quay.io/ocpmetal/assisted-installer-controller@sha256:20f38f2f29f7bded275ee27ed2702b391e8e09b034fd96bf7bfd1b158978c38b"
  