---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "30"

#commonAnnotations:
#  argocd.argoproj.io/sync-wave: "30"

resources:
  - 05-agentserviceconfig.yaml
  - 05-assisted-pull-secret.yaml
  - 06-bmc-hypervisor4-sushy.yaml